spring:
  application:
    name: conference-planning
  datasource:
    url: jdbc:postgresql://localhost:32768/conference
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true

server:
  port: 8090

logging:
  file:
    name: conference.log
